[feature/camera] 카메라 기능 구현, ml kit custom model 적용
snusun/MCA-Team1 pull request #7
Opened 2021-10-18 17:28 UTC by snusun

- cameraX API를 이용하여 camera 기능을 구현
- ml kit custom model을 적용하여 기존 ml kit model 보다 세부적인 object detection이 가능
- live camera 화면에서 실시간으로 object detection이 가능하고, bounding box로 표현됨

2021-10-19 09:37 UTC, ccdc-git commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.INTERNET"/>
인터넷이 필요한가요?

2021-10-19 09:40 UTC, ccdc-git commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
WRITE_EXTERNAL_STORAGE를 받으면 자동으로 READ권한도 생겨요.
둘다 명시하는게 보기 편하면 그냥 두어도 됩니다.

2021-10-19 09:46 UTC, ccdc-git commented on app/src/main/java/com/example/aganada/camera/CameraXActivity.kt
> +        val targetResolution = PreferenceUtils.getCameraXTargetResolution(this, lensFacing)
미리보기 화질이 낮아요

2021-10-19 09:49 UTC, ccdc-git requested changes
.gitignore로 지웠던 파일들이 부활했네요.
https://stackoverflow.com/a/19095988 여기 다른 파일들 무시하는 방법 있으니까 참고해주세요.

MainActivity 하나에서 fragment를 이동하는걸로 아는데 Camera는 따로 Activity를 만드는 건가요?

2021-10-20 16:39 UTC, snusun commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.INTERNET"/>
이게 왜 생겼지?? 없앴어요

2021-10-20 17:15 UTC, snusun commented
> .gitignore로 지웠던 파일들이 부활했네요. https://stackoverflow.com/a/19095988 여기 다른 파일들 무시하는 방법 있으니까 참고해주세요.

감사합니다!! 안그래도 찾고 있었어요
 
> MainActivity 하나에서 fragment를 이동하는걸로 아는데 Camera는 따로 Activity를 만드는 건가요?

넵 Camera Activity가 있는 편이 나을 것 같아서 따로 만들었습니다

2021-10-25 08:23 UTC, juimdpp commented on app/src/main/AndroidManifest.xml
>              </intent-filter>
카메라 activity가 첫 화면으로 뜨는데 이건 의도하신건가요??

2021-10-25 08:31 UTC, juimdpp approved these changes
좋습니다! 수고했어요

2021-10-25 09:32 UTC, snusun commented on app/src/main/AndroidManifest.xml
>              </intent-filter>
네! 시작 화면이 카메라 화면이거든요! 현수님께서 사진 촬영 구현하시고 카메라 activity에서 main activity로 넘어가게 구현해주시면 됩니다!

2021-10-25 09:48 UTC, ccdc-git approved these changes
수고하셨습니다.

2021-10-25 09:49 UTC, merged